### ISSUE TITLE
I don't know how to accurately describe this issue for a title.

### ISSUE THREAD

**Issue by grantlmul** [soruly/trace.moe#71]
Original image does not work:
![2020-05-08-monitor-hd](https://user-images.githubusercontent.com/39559405/123524423-2475b900-d698-11eb-9688-b1b002dbf633.png)

Modified image works fine:
![what](https://user-images.githubusercontent.com/39559405/123524430-2c355d80-d698-11eb-9017-29eb7b84b1de.png)

**Comment by soruly** [comment]
Hi grantlmul, the algorithm cannot detect which part of the image is (not) an anime. It always assume the whole image is an anime screenshot. That's why you need to crop the region that you think is anime manually. This is a limitation of the search engine.
 The auto crop border function only works on plain black borders.
