### ISSUE TITLE
Older Anime and recognition suggestions

### ISSUE THREAD

**Issue by randoomdude** [soruly/trace.moe#75]
I was putting in an image earlier that I knew what show it was from, a screenshot from Maison Ikkoku (1986), I was just looking for the timestamp. trace.moe doesn't seem to be as accurate the further back you go, but it got the search incorrect, which made me wonder if it might help that if it gets it wrong, you can let it know or say what show it's supposed to be from if you know, just a suggestion

**Comment by soruly** [comment]
This search engine is not a neural network trained by machine learning, it's just a perceptual image hash database on large amonut of anime. The screenshots you submit are not useful in improving search accuracy because the database cannot index images without timestamp. So in order to make it "recognize" your image, you'll have to send me the original video so the database can index it.
